server:
  port: 8080
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/lair?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      #空闲连接超时时长
      idle-timeout: 60000
      #连接超时时长
      connection-timeout: 60000
      #最大生命周期，0不过期
      max-lifetime: 0
      #最小空闲连接数
      minimum-idle: 10
      #最大连接数量
      maximum-pool-size: 10
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    open-in-view: false
  freemarker:
    check-template-location: false
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 6000ms
    lettuce:
      pool:
        max-active: 1000  # The maximum number of connections in the connection pool (use a negative value to indicate no limit)
        max-wait: 10000ms      # Connection pool maximum blocking wait time (use a negative value to indicate no limit)
        max-idle: 10      # Maximum idle connections in the connection pool
        min-idle: 5       # Minimum idle connection in connection pool
