name: Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'docs:')"

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2

      - name: Install node
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          dest: docs

      - name: Install
        run: pnpm -C docs install

      - name: Run Build
        run: pnpm run build

      - name: echo cname
        run: echo 'lair.elonehoo.xyz' > docs/.vitepress/dist/CNAME

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: docs/.vitepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
